using System.Collections.Generic;
using System.Linq;
using DLS.Description;

namespace DLS.Game
{
	public class ChipLibrary
	{
		public readonly List<ChipDescription> allChips = new();

		readonly HashSet<string> builtinChipNames = new(ChipDescription.NameComparer);
		readonly Dictionary<string, ChipDescription> descriptionFromNameLookup = new(ChipDescription.NameComparer);

		readonly List<ChipDescription> hiddenChips = new();

		public ChipLibrary(ChipDescription[] customChips, ChipDescription[] builtinChips)
		{
			// Add built-in chips to list of all chips
			foreach (ChipDescription chip in builtinChips)
			{
				// Bus terminus chip should not be shown to the user (it is created automatically upon placement of a bus start point)
				bool hidden = ChipTypeHelper.IsBusTerminusType(chip.ChipType) || chip.ChipType == ChipType.dev_Ram_8Bit;

				AddChipToLibrary(chip, hidden);
				builtinChipNames.Add(chip.Name);
			}

			// Add custom chips to list of all chips
			foreach (ChipDescription chip in customChips)
			{
				AddChipToLibrary(chip);
			}

			RebuildChipDescriptionLookup();
			foreach (ChipDescription chip in customChips) FillMissingOutputPinColours(chip);
		}

		// A sub-chip saved without output-pin colour info (chips generated by the optimisation tools used to
		// write null there) is given the default entry per output pin — exactly what a live instance
		// re-creates — so that opening such a chip doesn't show it as modified. Buses stay null on purpose.
		public void FillMissingOutputPinColours(ChipDescription chip)
		{
			if (chip?.SubChips == null) return;
			for (int i = 0; i < chip.SubChips.Length; i++)
			{
				ref SubChipDescription sub = ref chip.SubChips[i];
				if (sub.OutputPinColourInfo != null) continue;
				if (!descriptionFromNameLookup.TryGetValue(sub.Name, out ChipDescription subDesc)) continue;
				if (ChipTypeHelper.IsBusType(subDesc.ChipType)) continue;
				PinDescription[] outs = subDesc.OutputPins ?? System.Array.Empty<PinDescription>();
				sub.OutputPinColourInfo = outs.Select(p => new OutputPinColourInfo(p.Colour, p.ID)).ToArray();
			}
		}

		void RebuildChipDescriptionLookup()
		{
			descriptionFromNameLookup.Clear();
			foreach (ChipDescription desc in allChips)
			{
				descriptionFromNameLookup.Add(desc.Name, desc);
			}

			foreach (ChipDescription desc in hiddenChips)
			{
				descriptionFromNameLookup.Add(desc.Name, desc);
			}
		}


		public bool IsBuiltinChip(string name) => builtinChipNames.Contains(name);

		public bool HasChip(string name) => TryGetChipDescription(name, out _);

		public ChipDescription GetChipDescription(string name) => descriptionFromNameLookup[name];

		public bool TryGetChipDescription(string name, out ChipDescription description) => descriptionFromNameLookup.TryGetValue(name, out description);

		// When set (by Project), returns the LIVE (possibly unsaved) description of a chip that is currently
		// open in memory, so the SIMULATION reflects unsaved edits to sub-chips. Save/structure logic keeps
		// using the saved descriptions above.
		public System.Func<string, ChipDescription> SimOverride;

		public ChipDescription GetChipDescriptionForSim(string name)
		{
			ChipDescription live = SimOverride?.Invoke(name);
			if (live != null) return live;
			return descriptionFromNameLookup.TryGetValue(name, out ChipDescription d) ? d : null; // null = unresolved (stale ref)
		}

		public void RemoveChip(string chipName)
		{
			allChips.RemoveAll(c => c.NameMatch(chipName));
			RebuildChipDescriptionLookup();
		}

		public void NotifyChipSaved(ChipDescription description)
		{
			// Replace chip description if already exists
			bool foundChip = false;

			for (int i = 0; i < allChips.Count; i++)
			{
				if (allChips[i].NameMatch(description.Name))
				{
					allChips[i] = description;
					foundChip = true;
					break;
				}
			}

			// Otherwise add as new description
			if (!foundChip) AddChipToLibrary(description);

			RebuildChipDescriptionLookup();
			FillMissingOutputPinColours(description);
		}

		public void NotifyChipRenamed(ChipDescription description, string nameOld)
		{
			// Replace chip description
			for (int i = 0; i < allChips.Count; i++)
			{
				if (allChips[i].NameMatch(nameOld))
				{
					allChips[i] = description;
					break;
				}
			}

			RebuildChipDescriptionLookup();
		}

		public string[] GetAllCustomChipNames()
		{
			List<string> customChipNames = new();

			foreach (ChipDescription chip in allChips)
			{
				if (!IsBuiltinChip(chip.Name))
				{
					customChipNames.Add(chip.Name);
				}
			}

			return customChipNames.ToArray();
		}

		// Returns the descriptions of all chips that use the given chip as a direct subchip
		public ChipDescription[] GetDirectParentChips(string chipName)
		{
			List<ChipDescription> parents = new();

			foreach (ChipDescription other in allChips)
			{
				if (other.SubChips == null) continue;
				if (other.SubChips.Any(subchip => ChipDescription.NameMatch(subchip.Name, chipName)))
				{
					parents.Add(other);
				}
			}

			return parents.ToArray();
		}

		void AddChipToLibrary(ChipDescription description, bool hidden = false)
		{
			if (hidden) hiddenChips.Add(description);
			else allChips.Add(description);
		}
	}
}